### ISSUE TITLE
e01_simple.html | Uncaught Error: NoSuchMethodError: method not found: 'whenPolymerReady'

### ISSUE THREAD

**Issue by damondouglas** [bwu-dart/bwu_datagrid#111]
The dartium console window shows the following when navigating to e01_simple.html.  Is this possibly related to #110?

```
Found bad packages uri in html import. All packages uris should point to the
packages symlink in the same folder as the entry point.

Entry point: http://localhost:8000/example/e01_simple.html
Owner document: http://localhost:8000/example/src/e01_simple/app_element.html
Current import: <link rel="import" href="../../../packages/polymer/polymer.html">
Corrected import: <link rel="import" href="../../packages/polymer/polymer.html">

For more information, please see:
https://www.dartlang.org/polymer/app-directories.html#into-a-non-dart-non-entry-point

Found bad packages uri in html import. All packages uris should point to the
packages symlink in the same folder as the entry point.

Entry point: http://localhost:8000/example/e01_simple.html
Owner document: http://localhost:8000/example/src/e01_simple/app_element.html
Current import: <link rel="import" href="../../../packages/bwu_datagrid/bwu_datagrid.html">
Corrected import: <link rel="import" href="../../packages/bwu_datagrid/bwu_datagrid.html">

For more information, please see:
https://www.dartlang.org/polymer/app-directories.html#into-a-non-dart-non-entry-point

undefined:1 Exception: Uncaught Error: NoSuchMethodError: method not found: 'whenPolymerReady'
Receiver: Instance of 'JsObject'
Arguments: [Closure: () => dynamic]
Stack Trace:
#0      JsObject.callMethod (dart:js:230)
#1      PolymerJs.whenPolymerReady (package:polymer_interop/polymer_interop.dart:56:14)
#2      _hookJsPolymer (package:polymer/src/loader.dart:71:13)
#3      startPolymer.<anonymous closure> (package:polymer/src/loader.dart:36:5)
#4      dirtyCheckZoneSpec.wrapUnaryCallback.<anonymous closure> (package:observe/src/dirty_check.dart:120:15)
#5      _rootRunUnary (dart:async/zone.dart:902)
#6      _CustomZone.runUnary (dart:async/zone.dart:804)
#7      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:494)
#8      _Future._propagateToListeners (dart:async/future_impl.dart:577)
#9      _Future._completeWithValue (dart:async/future_impl.dart:368)
#10     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:422)
#11     dirtyCheckZoneSpec.wrapCallback.<anonymous closure> (package:observe/src/dirty_check.dart:111:15)
#12     _rootRun (dart:async/zone.dart:895)
#13     _CustomZone.run (dart:async/zone.dart:796)
#14     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:731)
#15     _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#16     _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#17     _ScheduleImmediateHelper._handleMutation (dart:html:42407)
```

**Comment by zoechi** [comment]
Sorry I didn't respond to your issue. I tried hard to get things fixed to be able to work on bwu-datagrid. Took waaay longer than I anticipated :(
I'm currently upgrading to Polymer 1.0. If you run into this again please add a comment and I'll check it again.
