### ISSUE TITLE
e07_events example update with context menu not working properly

### ISSUE THREAD

**Issue by zoechi** [bwu-dart/bwu_datagrid#132]
after choosing a priority using the context menu, the value is only updated after clicking into the cell.

**Comment by zoechi** [comment]
console logs

> Uncaught Unhandled exception:
type 'EventImpl' is not a subtype of type 'CustomEvent' of 'e' where
  EventImpl is from dart:html
  CustomEvent is from dart:html
>
#0      AppElement.attached.<anonymous closure>.<anonymous closure> (package:bwu_datagrid_examples/e07_events/app_element.dart:77:38)
#1      JsObject._callMethodLegacy (dart:js:1148)
#2      JsObject.callMethod (dart:js:1137)
#3      HtmlElement&PolymerMixin&PolymerBase.fire (package:polymer_interop/src/polymer_base.dart:142:36)
#4      ContextMenu.attached.<anonymous closure> (package:bwu_datagrid_examples/e07_events/context_menu.dart:34:7)
