### ISSUE TITLE
e09_row_reordering dropping to the recycle bin doesn't work

### ISSUE THREAD

**Issue by zoechi** [bwu-dart/bwu_datagrid#139]
A weird ever-increasing (on-mousemove) drag image is shown and drag-over the recycle bin has no effect.

**Comment by zoechi** [comment]
> 2e09_row_reordering.html:1 Uncaught Unhandled exception:
The null object does not have a getter 'style'.
>
NoSuchMethodError: method not found: 'style'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      RowMoveManager._handleDrag (package:bwu_datagrid/plugins/row_move_manager.dart:122:21)
#3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1138)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:334)
#5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:261)
#6      _SyncBroadcastStreamController._sendData.<anonymous closure> (dart:async/broadcast_stream_controller.dart:394)
#7      _BroadcastStreamController._forEachListener (dart:async/broadcast_stream_controller.dart:335)
#8      _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:393)
#9      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:261)
#10     EventBus.fire (package:bwu_datagrid/core/event_bus.dart:50:16)
#11     BwuDatagrid._handleDrag (package:bwu_datagrid/bwu_datagrid.dart:2803:38)

**Comment by zoechi** [comment]
The exception is fixed (caused by delayed creation of `_selectionProxy` and `_guide` to work around a browser issue that causes dnd to break if the DOM is modified inside the dragStart event handler.

The ever-increasing drag proxy image is only in Dartium but not in Chrome.

Dropping onto "Recycle bin" still doesn't delete the rows.
