### ISSUE TITLE
Columns pile up into one column when we navigate away from the grid then come back.

### ISSUE THREAD

**Issue by tonosama-atlacatl** [bwu-dart/bwu_datagrid#146]
We are trying to use bwu_datagrid in our application, but when we “navigate away” to a different internal page, and come back again, the data columns are all piled up on the left side.  The column headers still look okay.  

In a different experimental application over a year ago, we had a similar problem and found a solution by adding our own “reshowGrid” function to our own copy of bwu_datagrid.  Each time our grid was about to be shown, we called "grid.reshowGrid()".  Applying the same concept to our current application has solved this problem, too.  Here is the code that we’ve added to bwu_datagrid:

```
void reshowGrid() {
  if (_initialized) {
    invalidateAllRows();
    //_createColumnHeaders();
    _removeCssRules();
    _createCssRules();
    resizeCanvas();
    _applyColumnWidths();

    _handleScroll();
  }
}
```
The reshowGrid function is basically the last part of the setColumns function, but we’ve commented out the call to _createColumnHeaders (we found that we didn’t need it, anyway).  That function was giving the following exception:

```
Uncaught Unhandled exception:
type 'StyleElementImpl' is not a subtype of type 'BwuDatagridHeaderColumn' in type cast.
#0      Object._as (dart:core-patch/object_patch.dart:67)
#1      BwuDatagrid._createColumnHeaders.<anonymous closure> (package:bwu_datagrid/bwu_datagrid.dart:766:29)
#2      Object&ListMixin.forEach (dart:collection/list.dart:63)
#3      BwuDatagrid._createColumnHeaders (package:bwu_datagrid/bwu_datagrid.dart:764:10)
#4      BwuDatagrid.reshowGrid (package:bwu_datagrid/bwu_datagrid.dart:1647:7)
#5      TwDataGridNG.attached (package:tw_ui_polymer/components/datagrid_ng/datagrid.dart:227:12)
```

We would appreciate you adding this public function (or something equivalent) to bwu_datagrid.  I’m sure we are not the only ones who will need it.

Thank you

**Comment by zoechi** [comment]
Thanks for reporting. I'll have a look.

**Comment by gtaylor20** [comment]
I think the "Unhandled exception for the 'StyleElementImpl' " error is coming from your utils.closest function, where you do a querySelectorAll.  In Polymer 1.0, now, the <style> element also has the .bwu-datagrid-header-column class.  I did not do a detailed analysis of your code, but I think this is the culprit.  I hope this helps.

**Comment by gtaylor20** [comment]
Thanks for all the help on issue #144.  Now, on to this one again. :-)
I have recreated the problem using your e01_simple example.  I modified it to show the grid in a paper-dialog.  I had to add the dependency for polymer_elements to the pubspec.yaml to get paper-dialog downloaded for the project.

Here is my new app_element.html:
```
<dom-module id='app-element'>
  <template>
    <style include="example-style"></style>
    <options-panel source-dir="e01_simple">
      <!--<bwu-datagrid grid id='myGrid' theme="example-style"></bwu-datagrid>-->
      <span class="title">
        Basic grid with minimal configuration
      </span>
      <button on-click="toggleDialog">Toggle Dialog</button>
      <button on-click="reshowGrid">Reshow Grid</button>
      <paper-dialog id="dialog" no-cancel-on-outside-click>
        <bwu-datagrid grid id='myGrid' theme="example-style"></bwu-datagrid>
      </paper-dialog>
    </options-panel>
  </template>
</dom-module>
```
Then, in the app_element.dart file, I imported the paper_dialog, and added GridOptions:  autoHeight: true, forceFitColumns: true.  I also added these functions for the button clicks:
```
  @reflectable
  toggleDialog(var e, var detail) {
    $$('#dialog').toggle();
  }

  @reflectable
  reshowGrid(var e, var detail) {
    $$('#myGrid').reshowGrid();
  }
```
When you first click on Toggle Dialog, the grid appears in the dialog with the piled-up columns.  Clicking Reshow Grid button, calls my "reshowGrid()" function as shown earlier.  This causes the columns and data to appear properly.  Now, you can click Toggle Dialog repeatedly and the grid appears okay.  However, if you click Reshow Grid while the dialog is not visible, it will squish again.  So, you need to click Reshow Grid to get the columns and data back again.  

I hope this helps you to be able to see the problem and provide us with a "reshowGrid" function or something similar.  Or, even better, be able to fix the issue internally so that we don't have to worry about it at all. :-)

**Comment by zoechi** [comment]
Similar to #97
